CREATE DATABASE PESHO;
USE PESHO;

CREATE TABLE SHIRTS(
    ID INTEGER NOT NULL AUTO_INCREMENT, PRIMARY KEY(ID),
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(255) NOT NULL,
    shirtSize VARCHAR(255) NOT NULL,
    shirtColor VARCHAR(255) NOT NULL
);